apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: harbor.deemoprobe.com/devops/mytest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: web
  labels:
    app: myapp
  name: myapp  
spec:
  selector:
    app: myapp
  ports:
  - port: 8081
    targetPort: 8080
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: web
  name: myapp
spec:
  ingressClassName: ingress
  rules:
  - host: myapp.pipeline.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp
            port:
              number: 8081
